language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

env:
  - DJANGO_VERSION='>=1.8,<1.9'
  - DJANGO_VERSION='>=1.9,<1.10'
  - DJANGO_VERSION='>=1.10,<1.11'
  - DJANGO_VERSION='>=1.11,<2.0'
  - DJANGO_VERSION='>=2.0,<2.1'
  - DJANGO_VERSION='>=2.1,<2.2'

notifications:
  email: false

install:
  - pip install -r .travis-requirements.txt
  - pip install Django$DJANGO_VERSION

script:
  - python runtests.py

matrix:
  exclude:
    - python: "2.7"
      env: DJANGO_VERSION='>=2.0,<2.1'
    - python: "2.7"
      env: DJANGO_VERSION='>=2.1,<2.2'
    - python: "3.4"
      env: DJANGO_VERSION='>=2.1,<2.2'
