# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-07 08:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_sofortueberweisung', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SofortRefund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=255, verbose_name='status')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title')),
                ('pain', models.TextField(verbose_name='PAIN base64')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='last modified')),
            ],
        ),
        migrations.AlterModelOptions(
            name='soforttransaction',
            options={'verbose_name': 'Sofort transaction', 'verbose_name_plural': 'Sofort transactions'},
        ),
        migrations.AddField(
            model_name='sofortrefund',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='django_sofortueberweisung.SofortTransaction', verbose_name='Transaction'),
        ),
    ]
